#!/usr/bin/env bash
# A bash script that prints information about subdomains.

function get_sub_info {
  local domain=$1
  local subdomain=$2
  local full_domain="${subdomain}.${domain}"
  echo "Checking ${full_domain}..."
  
  # Capture the IP address using dig
  local record_ip=$(dig +short ${full_domain})

  # Print the raw result for debugging
  echo "dig +short ${full_domain}: ${record_ip}"

  if [[ -z "$record_ip" ]]; then
    echo "No IP address found for ${full_domain}"
    return
  fi

  echo "The subdomain ${subdomain} is a A record and points to ${record_ip}"
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  for sub in www lb-01 web-01 web-02; do
    get_sub_info $domain $sub
  done
else
  get_sub_info $domain $subdomain
fi
